#-------------------------------------------------------------------------------
# Plugins
#-------------------------------------------------------------------------------

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'



# ------------------------------------------------
# Utility
# ------------------------------------------------

[[plugins]]
repo = 'yuroyoro/smooth_scroll.vim'

[[plugins]]
repo = 'vim-scripts/smartword'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'vim-scripts/matchit.zip'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'airblade/vim-gitgutter'



# ------------------------------------------------
# Syntax
# ------------------------------------------------

[[plugins]]
repo = 'itchyny/vim-autoft'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = 'haskell'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'



# ------------------------------------------------
# Colorscheme
# ------------------------------------------------

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-scripts/Zenburn'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'mopp/mopkai.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'reedes/vim-colors-pencil'



# ------------------------------------------------
# Statusline
# ------------------------------------------------

[[plugins]]
repo = 'itchyny/lightline.vim'



# ------------------------------------------------
# Completion
# ------------------------------------------------

[[plugins]]
repo = 'neoclide/coc.nvim'



# ------------------------------------------------
# Quickrun.vim
# ------------------------------------------------

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'mattn/emmet-vim'
